[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "foo"
version = "0.0.1"
description = "A small example package"
requires-python = ">=3.12"

